// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/test": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/:pid": {
    params: {
      "pid": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/test" | "/products" | "/products/:pid";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/test.tsx": {
    id: "routes/test";
    page: "/test";
  };
  "routes/plp.tsx": {
    id: "routes/plp";
    page: "/products";
  };
  "routes/product.tsx": {
    id: "routes/product";
    page: "/products/:pid";
  };
};